# Site settings
title: Trials of a Lead Developer
email: alex.hopgood+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer trials in a modern London startup
  Balancing legacy code with new technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: AlexHopgood
github_username:  ahopgood

# Build settings
markdown: kramdown
