services:
  jekyll:
    build:
      context: .
    image: jekyll-local:latest
    pull_policy: build
    environment:
      - FUTURE=true
      - DRAFT=true
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll